# Generated by Django 2.2.4 on 2019-08-02 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
            preserve_default=False,
        ),
    ]
